### ISSUE TITLE
Android CashSDK Release 1.4

### ISSUE THREAD

**Issue by dabitdev** [atmcoin/cash-sdk-android#16]
Changes:
- Fix issue were the `CashSDK` was showing valid session when the session was not created due to an http error. https://github.com/atmcoin/cash-sdk-android/pull/14
- Fixed the issue where the AtmList by location was not working because the params were inverted. https://github.com/atmcoin/cash-sdk-android/pull/13
- Initial UnitTest coverage by @anasoid https://github.com/atmcoin/cash-sdk-android/pull/12

**Comment by dabitdev** [comment]
@anasoid I would like to put a test coverage badge in the repository as soon as we get the first set of tests. The CashSDK has his own CI, the badge could come from jacoco / sonar. 

Something like the image below, what do you think?

<img width="200" alt="Screen Shot 2020-06-18 at 3 19 36 PM" src="https://user-images.githubusercontent.com/142539/85062851-3c5a5900-b177-11ea-8d44-bbf0a87968d0.png">

**Comment by anasoid** [comment]
Yes we can add it like this, thi is real values from cash SDK sonarcloud

[![Sonarcloud Status](https://sonarcloud.io/api/project_badges/measure?project=atmcoin_cash-sdk-android&metric=alert_status)](https://sonarcloud.io/dashboard?id=atmcoin_atmcoin_cash-sdk-android) 
[![SonarCloud Coverage](https://sonarcloud.io/api/project_badges/measure?project=atmcoin_cash-sdk-android&metric=coverage)](https://sonarcloud.io/component_measures/metric/coverage/list?id=atmcoin_atmcoin_cash-sdk-android)
[![SonarCloud Bugs](https://sonarcloud.io/api/project_badges/measure?project=atmcoin_cash-sdk-android&metric=bugs)](https://sonarcloud.io/component_measures/metric/reliability_rating/list?id=atmcoin_atmcoin_cash-sdk-android)
[![SonarCloud Vulnerabilities](https://sonarcloud.io/api/project_badges/measure?project=atmcoin_cash-sdk-android&metric=vulnerabilities)](https://sonarcloud.io/component_measures/metric/security_rating/list?id=atmcoin_atmcoin_cash-sdk-android)

May be we should also add last version on maven repo and bintary like https://github.com/mockito/mockito
